pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                echo 'Checking out source code from GitHub repository'
            }
        }

        stage('Install Dependencies') {
            steps {
                echo 'Installing Node.js dependencies'
                sh 'npm install'
            }
        }

        stage('Vulnerability Scan using npm audit') {
            steps {
                echo 'Running vulnerability scan using npm audit'
                sh 'npm audit || true'
            }
        }

        stage('Review Vulnerabilities') {
            steps {
                echo 'Reviewing vulnerability report generated by npm audit'
            }
        }

        stage('Optional Fix') {
            steps {
                echo 'Attempting to fix vulnerabilities using npm audit fix'
                sh 'npm audit fix || true'
            }
        }

        stage('Report Generation') {
            steps {
                echo 'Security scan report reviewed in Jenkins console output'
            }
        }

        stage('Pipeline Completion') {
            steps {
                echo 'Vulnerability scanning pipeline completed successfully'
            }
        }
    }
}
